import {
  Archive,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  CalendarCheck,
  CalendarDays,
  Check,
  Circle,
  Code,
  Droplet,
  Dumbbell,
  FileText,
  FileX,
  Folder,
  FolderX,
  Footprints,
  GraduationCap,
  Heart,
  House,
  Inbox,
  Languages,
  ListChecks,
  Moon,
  Music,
  Palette,
  Pill,
  Plane,
  Plus,
  Repeat,
  Rocket,
  ShoppingCart,
  Sparkles,
  Sun,
  Timer,
  type LucideIcon,
} from 'lucide-react'

/**
 * Icons addressable by name.
 *
 * Projects and habits store their icon as a string, so something has to map
 * that string to a component. Doing it with `import * as lucide` works, but it
 * defeats tree-shaking and drags all ~1,500 icons into the bundle — about a
 * megabyte for the two dozen we actually offer. This list is that price paid
 * honestly: add an icon here before offering it in a picker.
 */
export const ICON_REGISTRY: Record<string, LucideIcon> = {
  Archive,
  Book,
  BookOpen,
  Brain,
  Briefcase,
  CalendarCheck,
  CalendarDays,
  Check,
  Circle,
  Code,
  Droplet,
  Dumbbell,
  FileText,
  FileX,
  Folder,
  FolderX,
  Footprints,
  GraduationCap,
  Heart,
  House,
  Inbox,
  Languages,
  ListChecks,
  Moon,
  Music,
  Palette,
  Pill,
  Plane,
  Plus,
  Repeat,
  Rocket,
  ShoppingCart,
  Sparkles,
  Sun,
  Timer,
}
